---
- name: Kong Utility Tool
  hosts: all
  become: yes
  tasks:
    - name: Kong stop
      shell: |
        kong stop 
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin"  # Add the path to kong if necessary
      args:
        executable: /bin/bash
      become: yes
      become_user: root
      register: kong_stop
      ignore_errors: true
      tags: 
        - stop

    - name: Debug Kong stop Output
      debug:
        msg: "Kong stop command output: {{ kong_stop.stdout | default('No output') }}"
      when: kong_stop is defined
      tags: 
        - stop

    - name: Kong start
      shell: |
        kong start -c /etc/kong/kong.conf
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin"  # Add the path to kong if necessary
      args:
        executable: /bin/bash
      become: yes
      become_user: root
      register: kong_start
      ignore_errors: true
      tags: 
        - start

    - name: Debug Kong restart Output
      debug:
        msg: "Kong start command output: {{ kong_start.stdout | default('No output') }}"
      when: kong_start is defined
      tags: 
        - start

    
    - name: Kong restart
      shell: |
        kong restart -c /etc/kong/kong.conf
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin"  # Add the path to kong if necessary
      args:
        executable: /bin/bash
      become: yes
      become_user: root
      register: kong_restart
      ignore_errors: true
      tags: 
        - restart

    - name: Debug Kong restart Output
      debug:
        msg: "Kong restart command output: {{ kong_restart.stdout | default('No output') }}"
      when: kong_restart is defined
      tags: 
        - restart
    
    - name: Kong Status
      shell: |
        kong health 
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin"  # Add the path to kong if necessary
      args:
        executable: /bin/bash
      become: yes
      become_user: root
      register: kong_health
      ignore_errors: true
      tags: 
        - status

    - name: Debug Kong health Output
      debug:
        msg: "Kong health command output: {{ kong_health.stdout | default('No output') }}"
      when: kong_health is defined
      tags: 
        - status